auth_enabled: false

server:
  http_listen_port: ${LOKI_PORT:-3100}

common:
  instance_addr: 127.0.0.1
  path_prefix: ${LOKI_DATA_DIR:-C:/loki-data}
  storage:
    filesystem:
      chunks_directory: ${LOKI_DATA_DIR:-C:/loki-data}/chunks
      rules_directory: ${LOKI_DATA_DIR:-C:/loki-data}/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

limits_config:
  retention_period: 168h

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
