apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

# GCP 전용 이미지 레지스트리 대체 (선택)
# GHCR 그대로 쓰려면 이 블록 삭제.
# images:
#   - name: ghcr.io/OWNER/loan-service
#     newName: asia-northeast3-docker.pkg.dev/PROJECT/banking/loan-service

commonAnnotations:
  cloud.google.com/load-balancer-type: "External"
