global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'customer-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'deposit-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'loan-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8083']

  - job_name: 'payment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8084']

  - job_name: 'master-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8085']

  - job_name: 'ai-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8086']
