-- ============================================================
-- V1 (H2 테스트 전용): 에이전트 감사 로그 테이블
-- PostgreSQL 전용 기능(트리거, GENERATED ALWAYS AS STORED, pg_column_size)
-- 은 H2 호환을 위해 제외. AuditImmutabilityEnforcer 가 H2 환경 자동 감지 후 skip.
-- ============================================================

CREATE TABLE IF NOT EXISTS agent_audit_log (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id              BIGINT          NOT NULL,
    schema_version      VARCHAR(10)     NOT NULL DEFAULT 'v1',
    track               VARCHAR(16)     NOT NULL,
    request_snapshot    CLOB            NOT NULL,
    opinion_json        CLOB            NOT NULL,
    tool_calls_json     CLOB            NOT NULL DEFAULT '[]',
    raw_llm_response    CLOB,
    pii_masked          BOOLEAN         NOT NULL DEFAULT TRUE,
    fallback_reason     VARCHAR(64),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retention_until     DATE            NOT NULL DEFAULT DATEADD('YEAR', 5, CURRENT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_aal_rev_id     ON agent_audit_log(rev_id);
CREATE INDEX IF NOT EXISTS idx_aal_created_at ON agent_audit_log(created_at DESC);
