CREATE TABLE psi_baseline (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_name   VARCHAR(128) NOT NULL,
    bucket_index   SMALLINT     NOT NULL,
    bucket_low     NUMERIC(18,6),
    bucket_high    NUMERIC(18,6),
    baseline_ratio NUMERIC(8,6) NOT NULL,
    baseline_date  DATE         NOT NULL,
    model_version  VARCHAR(64)  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_psi_baseline UNIQUE (feature_name, bucket_index, model_version)
);

CREATE TABLE psi_drift_result (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_name  VARCHAR(128) NOT NULL,
    calc_week     DATE         NOT NULL,
    psi_value     NUMERIC(8,6) NOT NULL,
    status        VARCHAR(16)  NOT NULL,
    sample_count  INT          NOT NULL,
    model_version VARCHAR(64)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_psi_week UNIQUE (feature_name, calc_week, model_version)
);
CREATE INDEX idx_pdr_feature_week ON psi_drift_result(feature_name, calc_week DESC);

CREATE TABLE fairness_report (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_month  DATE         NOT NULL,
    group_key     VARCHAR(64)  NOT NULL,
    approval_rate NUMERIC(5,4) NOT NULL,
    sample_count  INT          NOT NULL,
    overall_rate  NUMERIC(5,4) NOT NULL,
    rate_gap      NUMERIC(5,4) NOT NULL,
    flagged       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fairness UNIQUE (report_month, group_key)
);
CREATE INDEX idx_fr_month ON fairness_report(report_month DESC);
