-- ============================================================
-- V4 (H2 테스트 전용): RAG 임베딩 스토어
-- pgvector(vector 타입, IVFFlat, GIN, TSVECTOR)는 H2 미지원
-- → embedding = CLOB (JSON 배열), metadata = CLOB, fts_tokens 제외
-- RagSearchService 단위 테스트는 StubEmbeddingClient + in-memory 데이터 사용.
-- 하이브리드 검색 SQL 통합 테스트는 testcontainers + pgvector 별도 실행.
-- ============================================================

CREATE TABLE IF NOT EXISTS ai_embedding (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corpus          VARCHAR(30) NOT NULL,
    source_id       VARCHAR(200) NOT NULL,
    chunk_seq       SMALLINT    NOT NULL DEFAULT 0,
    chunk_text      CLOB        NOT NULL,
    chunk_summary   CLOB,
    embedding       CLOB,                               -- JSON 인코딩된 float 배열 (H2 호환)
    embedding_model VARCHAR(60) NOT NULL DEFAULT 'stub',
    metadata        CLOB        NOT NULL DEFAULT '{}',
    effective_date  DATE,
    expiry_date     DATE,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_embedding UNIQUE (corpus, source_id, chunk_seq, embedding_model)
);

CREATE INDEX IF NOT EXISTS ai_embedding_corpus_idx ON ai_embedding (corpus);
CREATE INDEX IF NOT EXISTS ai_embedding_active_idx ON ai_embedding (is_active);
