-- ============================================================
-- V9 (H2 테스트 전용): Admin 행위 감사 로그
-- INET 타입 미지원 → VARCHAR(45), JSONB → CLOB
-- ============================================================

CREATE TABLE IF NOT EXISTS admin_action_audit (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user      VARCHAR(128)    NOT NULL,
    action          VARCHAR(64)     NOT NULL,
    target_rev_id   BIGINT,
    request_body    CLOB,
    result          VARCHAR(32)     NOT NULL,
    failure_reason  TEXT,
    ip_address      VARCHAR(45),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_aaa_admin_user ON admin_action_audit(admin_user);
CREATE INDEX IF NOT EXISTS idx_aaa_created_at ON admin_action_audit(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_aaa_action     ON admin_action_audit(action);
